/**
 * Abstract Syntax Tree types for the expression engine
 *
 * The AST is a JSON-serializable intermediate representation
 * that can be:
 * - Serialized/deserialized
 * - Validated at schema level
 * - Generated by AI tools
 * - Inspected and transformed
 */

// ============================================================================
// Value Nodes - Represent values in expressions
// ============================================================================

/** A literal value (string, number, boolean, null) */
export interface LiteralNode {
  type: "literal";
  value: string | number | boolean | null;
}

/** A path reference to scope data (e.g., "context.user.name") */
export interface PathNode {
  type: "path";
  value: string;
  optional?: boolean; // For optional chaining (?.)
}

/** A reference to another value via $ prefix (e.g., $context.quantity) */
export interface RefNode {
  type: "ref";
  path: string;
}

/** Union of all value-producing nodes */
export type ValueNode = LiteralNode | PathNode | RefNode;

// ============================================================================
// Transform Nodes - Represent transformations
// ============================================================================

/** A single transform with optional arguments */
export interface TransformNode {
  type: "transform";
  name: string;
  args: ArgumentNode[];
}

/** An argument to a transform - can be a value or nested expression */
export type ArgumentNode = LiteralNode | RefNode | ExpressionNode;

// ============================================================================
// Expression Nodes - Represent complete expressions
// ============================================================================

/** A piped expression: source | transform | transform ... */
export interface PipeNode {
  type: "pipe";
  source: PathNode;
  transforms: TransformNode[];
}

/** A simple path without transforms */
export interface SimplePathNode {
  type: "simplePath";
  path: PathNode;
}

/** Top-level expression - either a pipe or simple path */
export type ExpressionNode = PipeNode | SimplePathNode;

// ============================================================================
// Root AST
// ============================================================================

/** The complete AST for an expression */
export interface ExpressionAST {
  /** The original expression string */
  source: string;
  /** The parsed AST */
  ast: ExpressionNode;
}

// ============================================================================
// Type Guards
// ============================================================================

export function isLiteralNode(node: unknown): node is LiteralNode {
  return (
    typeof node === "object" &&
    node !== null &&
    (node as LiteralNode).type === "literal"
  );
}

export function isPathNode(node: unknown): node is PathNode {
  return (
    typeof node === "object" &&
    node !== null &&
    (node as PathNode).type === "path"
  );
}

export function isRefNode(node: unknown): node is RefNode {
  return (
    typeof node === "object" &&
    node !== null &&
    (node as RefNode).type === "ref"
  );
}

export function isTransformNode(node: unknown): node is TransformNode {
  return (
    typeof node === "object" &&
    node !== null &&
    (node as TransformNode).type === "transform"
  );
}

export function isPipeNode(node: unknown): node is PipeNode {
  return (
    typeof node === "object" &&
    node !== null &&
    (node as PipeNode).type === "pipe"
  );
}

export function isSimplePathNode(node: unknown): node is SimplePathNode {
  return (
    typeof node === "object" &&
    node !== null &&
    (node as SimplePathNode).type === "simplePath"
  );
}

// ============================================================================
// AST Builders (Helpers)
// ============================================================================

export const AST = {
  literal: (value: string | number | boolean | null): LiteralNode => ({
    type: "literal",
    value,
  }),

  path: (value: string, optional = false): PathNode => ({
    type: "path",
    value,
    ...(optional && { optional }),
  }),

  ref: (path: string): RefNode => ({
    type: "ref",
    path,
  }),

  transform: (name: string, args: ArgumentNode[] = []): TransformNode => ({
    type: "transform",
    name,
    args,
  }),

  pipe: (source: PathNode, transforms: TransformNode[]): PipeNode => ({
    type: "pipe",
    source,
    transforms,
  }),

  simplePath: (path: PathNode): SimplePathNode => ({
    type: "simplePath",
    path,
  }),

  expression: (source: string, ast: ExpressionNode): ExpressionAST => ({
    source,
    ast,
  }),
};
